security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_MANAGER:       ROLE_USER
        ROLE_ADMIN:         ROLE_MANAGER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        hwi:
            id: my.custom.user_provider

    firewalls:
        main:
            pattern: ^/

            anonymous: true
            form_login:
                provider: fos_userbundle
                check_path: security_login_check
                login_path: security_login_form
                failure_path: security_login_form
                csrf_token_generator: security.csrf.token_manager

            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    vkontakte:          "/login/check-vkontakte"
                login_path:        security_login_form
                use_forward:       false
                failure_path:      security_login_form

                oauth_user_provider:
                    service: my.custom.user_provider


            logout:
                path: /logout
                target: /

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
